Drop rows where EmployeeName and JobTitle are 'Not provided'

Replace 'Not Provided' with 0 in BasePay OvertimePay OtherPay Benefits

Change BasePay OvertimePay OtherPay Benefits type to float

Display all employees name and basepay columns who have a BasePay greater than 200,000.

Find all employees whose JobTitle contains the word “Manager” (case = False)

Retrieve only the columns: EmployeeName, JobTitle, and TotalPay.

Find count of employees who have zero OvertimePay.

Calculate the TotalPay for each JobTitle where totalpay > 300000

Find the top 5 JobTitles with the highest average TotalPayBenefits show in descending order

Replace all missing Benefits values with 0

Identify the top employee name by TotalPay in each Year. Show year, employeename and totalpay dataframe

Find the number of employees per JobTitle.

In [17]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")


df = pd.read_csv("Salaries.csv")
df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [2]:
df = df[(df["EmployeeName"] != "Not provided") & (df["JobTitle"] != "Not provided")]
df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [3]:
df["BasePay"] = df["BasePay"].replace("Not Provided", 0)
df["OvertimePay"] = df["OvertimePay"].replace("Not Provided", 0)
df["OtherPay"] = df["OtherPay"].replace("Not Provided", 0)
df["Benefits"] = df["Benefits"].replace("Not Provided", 0)
df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [4]:
df["BasePay"] = df["BasePay"].astype(float)
df["OvertimePay"] = df["OvertimePay"].astype(float)
df["OtherPay"] = df["OtherPay"].astype(float)
df["Benefits"] = df["Benefits"].astype(float)
df.dtypes

Id                    int64
EmployeeName         object
JobTitle             object
BasePay             float64
OvertimePay         float64
OtherPay            float64
Benefits            float64
TotalPay            float64
TotalPayBenefits    float64
Year                  int64
Notes               float64
Agency               object
Status               object
dtype: object

In [5]:
high_pay = df[df["BasePay"] > 200000][["EmployeeName", "BasePay"]]
high_pay.head(10)

          EmployeeName    BasePay
2       ALBERT PARDINI  212739.13
7        DAVID KUSHNER  256576.96
9   JOANNE HAYES-WHITE  285262.00
12   EDWARD HARRINGTON  294580.02
13         JOHN MARTIN  271329.03
16            AMY HART  268604.57
19       ELLEN MOFFATT  257510.59
20          VENUS AZAR  257510.48
21        JUDY MELINEK  257510.44
25        GREGORY SUHR  256470.41

In [6]:
managers = df[df["JobTitle"].str.contains("Manager", case=False, na=False)]
managers.head(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
83,84,EDWARD REISKIN,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,230827.12,0.00,0.00,NaN,230827.12,230827.12,2011,NaN,San Francisco,NaN
87,88,KEVIN BARRY,MANAGER VII,96814.36,0.00,133563.47,NaN,230377.83,230377.83,2011,NaN,San Francisco,NaN
95,96,MIVIC HIROSE,MANAGER VIII,215180.76,0.00,12000.00,NaN,227180.76,227180.76,2011,NaN,San Francisco,NaN
162,163,JULIE LABONTE,MANAGER VIII,207501.20,0.00,2903.37,NaN,210404.57,210404.57,2011,NaN,San Francisco,NaN
168,169,AMPARO RODRIGUEZ,NURSE MANAGER,161044.00,4599.05,43997.82,NaN,209640.87,209640.87,2011,NaN,San Francisco,NaN
177,178,HARVEY ELWIN,MANAGER VIII,200385.64,0.00,8000.00,NaN,208385.64,208385.64,2011,NaN,San Francisco,NaN
182,183,SUSAN BUCHBINDER,MANAGER VIII,207874.94,0.00,0.00,NaN,207874.94,207874.94,2011,NaN,San Francisco,NaN
185,186,JOHN BROWN,MANAGER VIII,207798.79,0.00,0.00,NaN,207798.79,207798.79,2011,NaN,San Francisco,NaN
203,204,ROSELYN JEQUINTO,NURSE MANAGER,165996.75,8054.01,31660.13,NaN,205710.89,205710.89,2011,NaN,San Francisco,NaN

In [7]:
selected = df[["EmployeeName", "JobTitle", "TotalPay"]]
selected.head(10)

,EmployeeName,JobTitle,TotalPay
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,567595.43
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),538909.28
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),335279.91
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,332343.61
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",326373.19
5,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,316285.74
6,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",315981.05
7,DAVID KUSHNER,DEPUTY DIRECTOR OF INVESTMENTS,307899.46
8,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",303427.55
9,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",302377.73

In [8]:
no_overtime = df[df["OvertimePay"] == 0]
print("Total employees with 0 OvertimePay:", len(no_overtime))

Total employees with 0 OvertimePay: 77321

In [9]:
high_total = df[df["TotalPay"] > 300000][["JobTitle", "TotalPay"]]
high_total.head(10)

                                         JobTitle   TotalPay
0  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43
1                 CAPTAIN III (POLICE DEPARTMENT)  538909.28
2                 CAPTAIN III (POLICE DEPARTMENT)  335279.91
3            WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61
4    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19
5                       ASSISTANT DEPUTY CHIEF II  316285.74
6              BATTALION CHIEF, (FIRE DEPARTMENT)  315981.05
7                  DEPUTY DIRECTOR OF INVESTMENTS  307899.46
8              BATTALION CHIEF, (FIRE DEPARTMENT)  303427.55
9          CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)  302377.73

In [10]:
top_jobs = df.sort_values(by="TotalPayBenefits", ascending=False)[["JobTitle", "TotalPayBenefits"]].head(5)
top_jobs

                                              JobTitle  TotalPayBenefits
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY         567595.43
1                      CAPTAIN III (POLICE DEPARTMENT)         538909.28
110531                                  Deputy Chief 3         510732.68
110532                               Asst Med Examiner         479652.21
110533                        Chief Investment Officer         436224.36

In [11]:
df["Benefits"] = df["Benefits"].fillna(0)
df["Benefits"].head(10)

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
5    0.0
6    0.0
7    0.0
8    0.0
9    0.0
Name: Benefits, dtype: float64

In [12]:
# sort by year and pay
sorted_df = df.sort_values(by=["Year", "TotalPay"], ascending=[True, False])

# show the top employee for each year (first row of each year)
years = sorted_df["Year"].unique()

for y in years:
    print(sorted_df[sorted_df["Year"] == y][["Year", "EmployeeName", "TotalPay"]].head(1))

   Year    EmployeeName   TotalPay
0  2011  NATHANIEL FORD  567595.43
       Year    EmployeeName   TotalPay
36159  2012  Gary Altenberg  362844.66
       Year EmployeeName   TotalPay
72927  2013  Samson  Lai  347102.32
        Year EmployeeName   TotalPay
110531  2014  David Shinn  471952.64

In [13]:
job_counts = df["JobTitle"].value_counts()
job_counts.head(10)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Custodian                       2418
TRANSIT OPERATOR                2388
Firefighter                     2359
Recreation Leader               1971
Patient Care Assistant          1945
Name: count, dtype: int64